name: flutter_2d_game
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # analizer: any
  #analyzer: ^0.40.7
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4  
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.12
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/Background/BG.png
    - assets/Tiles/1.png
    - assets/Tiles/2.png
    - assets/Tiles/3.png
    - assets/Tiles/4.png
    - assets/Tiles/5.png
    - assets/Tiles/6.png
    - assets/Tiles/7.png
    - assets/Tiles/8.png
    - assets/Tiles/9.png
    - assets/Tiles/10.png
    - assets/Tiles/11.png
    - assets/Tiles/12.png
    - assets/Tiles/13.png
    - assets/Tiles/14.png
    - assets/Tiles/15.png
    - assets/Tiles/16.png
    - assets/Tiles/17.png
    - assets/Tiles/18.png
    - assets/Object/Bush (1).png
    - assets/Object/Bush (2).png
    - assets/Object/Bush (3).png
    - assets/Object/Bush (4).png
    - assets/Object/Crate.png
    - assets/Object/MushRoom_1.png
    - assets/Object/MushRoom_2.png
    - assets/Object/Sign_1.png
    - assets/Object/Sign_2.png
    - assets/Object/Stone.png
    - assets/Object/Tree_1.png
    - assets/Object/Tree_2.png
    - assets/Object/Tree_3.png
    - assets/NinjaGirl/Attack__000.png
    - assets/NinjaGirl/Attack__001.png
    - assets/NinjaGirl/Attack__002.png
    - assets/NinjaGirl/Attack__003.png
    - assets/NinjaGirl/Attack__004.png
    - assets/NinjaGirl/Attack__005.png
    - assets/NinjaGirl/Attack__006.png
    - assets/NinjaGirl/Attack__007.png
    - assets/NinjaGirl/Attack__008.png
    - assets/NinjaGirl/Attack__009.png
    - assets/NinjaGirl/Dead__000.png
    - assets/NinjaGirl/Dead__001.png
    - assets/NinjaGirl/Dead__002.png
    - assets/NinjaGirl/Dead__003.png
    - assets/NinjaGirl/Dead__004.png
    - assets/NinjaGirl/Dead__005.png
    - assets/NinjaGirl/Dead__006.png
    - assets/NinjaGirl/Dead__007.png
    - assets/NinjaGirl/Dead__008.png
    - assets/NinjaGirl/Dead__009.png
    - assets/NinjaGirl/Idle__000.png
    - assets/NinjaGirl/Idle__001.png
    - assets/NinjaGirl/Idle__002.png
    - assets/NinjaGirl/Idle__003.png
    - assets/NinjaGirl/Idle__004.png
    - assets/NinjaGirl/Idle__005.png
    - assets/NinjaGirl/Idle__006.png
    - assets/NinjaGirl/Idle__007.png
    - assets/NinjaGirl/Idle__008.png
    - assets/NinjaGirl/Idle__009.png
    - assets/NinjaGirl/Jump__000.png
    - assets/NinjaGirl/Jump__001.png
    - assets/NinjaGirl/Jump__002.png
    - assets/NinjaGirl/Jump__003.png
    - assets/NinjaGirl/Jump__004.png
    - assets/NinjaGirl/Jump__005.png
    - assets/NinjaGirl/Jump__006.png
    - assets/NinjaGirl/Jump__007.png
    - assets/NinjaGirl/Jump__008.png
    - assets/NinjaGirl/Jump__009.png
    - assets/NinjaGirl/Run__000.png
    - assets/NinjaGirl/Run__001.png
    - assets/NinjaGirl/Run__002.png
    - assets/NinjaGirl/Run__003.png
    - assets/NinjaGirl/Run__004.png
    - assets/NinjaGirl/Run__005.png
    - assets/NinjaGirl/Run__006.png
    - assets/NinjaGirl/Run__007.png
    - assets/NinjaGirl/Run__008.png
    - assets/NinjaGirl/Run__009.png
    - assets/NinjaGirl/Slide__000.png
    - assets/NinjaGirl/Slide__001.png
    - assets/NinjaGirl/Slide__002.png
    - assets/NinjaGirl/Slide__003.png
    - assets/NinjaGirl/Slide__004.png
    - assets/NinjaGirl/Slide__005.png
    - assets/NinjaGirl/Slide__006.png
    - assets/NinjaGirl/Slide__007.png
    - assets/NinjaGirl/Slide__008.png
    - assets/NinjaGirl/Slide__009.png
    - assets/MalePlayer/Dead__000.png
    - assets/MalePlayer/Dead__001.png
    - assets/MalePlayer/Dead__002.png
    - assets/MalePlayer/Dead__003.png
    - assets/MalePlayer/Dead__004.png
    - assets/MalePlayer/Dead__005.png
    - assets/MalePlayer/Dead__006.png
    - assets/MalePlayer/Dead__007.png
    - assets/MalePlayer/Dead__008.png
    - assets/MalePlayer/Dead__009.png
    - assets/MalePlayer/Idle__000.png
    - assets/MalePlayer/Idle__001.png
    - assets/MalePlayer/Idle__002.png
    - assets/MalePlayer/Idle__003.png
    - assets/MalePlayer/Idle__004.png
    - assets/MalePlayer/Idle__005.png
    - assets/MalePlayer/Idle__006.png
    - assets/MalePlayer/Idle__007.png
    - assets/MalePlayer/Idle__008.png
    - assets/MalePlayer/Idle__009.png
    - assets/MalePlayer/Jump__000.png
    - assets/MalePlayer/Jump__001.png
    - assets/MalePlayer/Jump__002.png
    - assets/MalePlayer/Jump__003.png
    - assets/MalePlayer/Jump__004.png
    - assets/MalePlayer/Jump__005.png
    - assets/MalePlayer/Jump__006.png
    - assets/MalePlayer/Jump__007.png
    - assets/MalePlayer/Jump__008.png
    - assets/MalePlayer/Jump__009.png
    - assets/MalePlayer/Run__000.png
    - assets/MalePlayer/Run__001.png
    - assets/MalePlayer/Run__002.png
    - assets/MalePlayer/Run__003.png
    - assets/MalePlayer/Run__004.png
    - assets/MalePlayer/Run__005.png
    - assets/MalePlayer/Run__006.png
    - assets/MalePlayer/Run__007.png
    - assets/MalePlayer/Run__008.png
    - assets/MalePlayer/Run__009.png
    - assets/MalePlayer/Slide__000.png
    - assets/MalePlayer/Slide__001.png
    - assets/MalePlayer/Slide__002.png
    - assets/MalePlayer/Slide__003.png
    - assets/MalePlayer/Slide__004.png
    - assets/MalePlayer/Slide__005.png
    - assets/MalePlayer/Slide__006.png
    - assets/MalePlayer/Slide__007.png
    - assets/MalePlayer/Slide__008.png
    - assets/MalePlayer/Slide__009.png
